server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: LosAngeles
          __path__: /var/log/nginx/*.log

  - job_name: backup
    static_configs:
      - targets:
          - localhost
        labels:
          job: backup
          host: LosAngeles
          __path__: /var/log/backup/*.log

  - job_name: observability
    static_configs:
      - targets:
          - localhost
        labels:
          job: observability
          host: LosAngeles
          __path__: /var/log/observability/*.log

  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          host: LosAngeles
          __path__: /var/log/syslog

  - job_name: fail2ban
    static_configs:
      - targets:
          - localhost
        labels:
          job: fail2ban
          host: LosAngeles
          __path__: /var/log/fail2ban.log

  - job_name: fail2ban_enriched
    static_configs:
      - targets:
          - localhost
        labels:
          job: fail2ban_enriched
          host: LosAngeles
          __path__: /var/log/security/fail2ban-enriched.log

  - job_name: auditd
    pipeline_stages:
      - drop:
          expression: 'type=(EXECVE|PROCTITLE)'
    static_configs:
      - targets:
          - localhost
        labels:
          job: auditd
          host: LosAngeles
          __path__: /var/log/audit/audit.log
