# 自动生成，请勿手动编辑。源文件: inventory/servers.yaml
all:
  hosts:
    LosAngeles:
      ansible_host: 23.185.200.12
      os: ubuntu-24.04
      cloud: crystalclear-solutions-llc
      region: us-ca-los-angeles
      ansible_host_public: 23.185.200.12
      ansible_user: as
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_losangeles
  children:
    prod:
      hosts:
        LosAngeles: {}
    monitor:
      hosts:
        LosAngeles: {}
    web:
      hosts:
        LosAngeles: {}
    docker_app:
      hosts:
        LosAngeles: {}
    proxy:
      hosts:
        LosAngeles: {}
