# 自动生成，请勿手动编辑。源文件: inventory/servers.yaml
all:
  hosts:
    prod-web-01:
      ansible_host: 172.16.x.x
      os: ubuntu-22.04
      cloud: aliyun
      region: cn-hangzhou
      ansible_host_public: x.x.x.x
    prod-monitor-01:
      ansible_host: 172.16.x.x
      os: ubuntu-22.04
      cloud: aliyun
      region: cn-hangzhou
    LosAngeles:
      ansible_host: 23.185.200.12
      os: ubuntu-24.04
      cloud: crystalclear-solutions-llc
      region: us-ca-los-angeles
      ansible_host_public: 23.185.200.12
      ansible_user: as
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_losangeles
  children:
    prod:
      hosts:
        prod-web-01: {}
        prod-monitor-01: {}
        LosAngeles: {}
    monitor:
      hosts:
        prod-monitor-01: {}
    web:
      hosts:
        prod-web-01: {}
        LosAngeles: {}
    docker_app:
      hosts:
        LosAngeles: {}
    proxy:
      hosts:
        LosAngeles: {}
