global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.qq.com:587
  smtp_from: 2695266624@qq.com
  smtp_auth_username: 2695266624@qq.com
  smtp_auth_identity: 2695266624@qq.com
  smtp_auth_password_file: /etc/alertmanager/smtp_password
  smtp_require_tls: true

route:
  receiver: email-ops
  group_by:
    - alertname
    - instance
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: email-ops
    email_configs:
      - to: 3177348309@qq.com
        send_resolved: true
        headers:
          Subject: '[LosAngeles][{{ .Status }}] {{ .CommonLabels.alertname }}'
